### ISSUE TITLE
No vclock support in put?

### ISSUE THREAD

**Issue by drone29a** [mmcgrana/clj-riak#1]
Hi Mark,

Forgive me if I'm being dense, but it doesn't look like clj-riak supports specifying the vclock parameter when put'ing a value that overwrites a preexisting one.  And I think this is required, but the Riak documentation might be outdated.

From the docs in the section on PUT:
http://wiki.basho.com/Basic-Riak-API-Operations.html

> Some request headers are required for PUTs:
> 
> Content-Type must be set for the stored object. Set what you expect to receive back when >next requesting it.
> X-Riak-Vclock if the object already exists, the vector clock attached to the object when read; >if the object is new, this header may be omitted

I noticed that if I rapidly (less than a ~2 second delay) put two different values into the same key, the first value wins and is not overwritten by the value that was written later.  I should be able to use the :vclock arg (retrieved from a get before the second put) to ensure that the last item written wins.

I can write a patch to add :vclock to unparse-object, but wanted to make sure I wasn't misunderstanding the issue.  Thanks for any input and happy new year!

**Comment by drone29a** [comment]
I referenced the REST API docs since I hadn't stumbled upon the PB version.

http://wiki.basho.com/PBC-API.html#Object-Key-Operations

Those indicate the the vclock is optional and only required if one wants to resolve sibling records.  I'm not sure if the vclock is also used to resolve the case I ran into when the bucket has allow_multi turned off.

**Comment by mmcgrana** [comment]
Hi Matt,

Your surprise at the the library missing a feature as fundamental as vector clock support is warranted, regardless of whether it is required or optional for put updates.

This library was designed mostly to facilitate experiments with the operational aspects of Riak and will definitely need some work if it's going to support production use. I've added you as a contributor so that you can apply patches straight away - let me know if you'd like me to look over anything. 

Happy new year to you too,
Mark

**Comment by drone29a** [comment]
Excellent, thank you.
